trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- task: PowerShell@2
  displayName: Creating clientname and clientvariable pairing
  inputs:
    targetType: 'inline'
    script: 'Install-Module ImportExcel -Scope CurrentUser -Force;$clientvar = Import-Excel $(Build.Repository.LocalPath)/ClientTestListwithMacro.xlsm | Select-Object -ExpandProperty ClientName;Write-Host "##vso[task.setvariable variable=clientname]$clientvar"'
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Azure subscription 1(c731920e-f389-4198-98b9-bb54ff8f6bde)'
    subscriptionId: 'c731920e-f389-4198-98b9-bb54ff8f6bde'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'RgPStest'
    location: 'East US'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/ranjitk92/ARMtemplates/master/azuredeploySQLserver_db_storagecontainer.json'
    overrideParameters: '-SQLname $(clientname) -DBname $(clientname) -blobstoragecontainer $(clientname) -clienttag $(clientname)'
    deploymentMode: 'Incremental'
  
- task: CmdLine@2
  displayName: Download DACPAC into Agent.TempDirectory
  inputs:
    script: 'mkdir TempDownload;cd ./TempDownload;curl -OL https://github.com/ranjitk92/TemplateDACPACTest/raw/master/basicdatabase.dacpac'
  
- task: SqlAzureDacpacDeployment@1
  inputs:
    azureSubscription: 'Azure subscription 1(c731920e-f389-4198-98b9-bb54ff8f6bde)'
    AuthenticationType: 'server'
    ServerName: '$(clientname).database.windows.net'
    DatabaseName: '$(clientname)'
    SqlUsername: 'ranjit1'
    SqlPassword: 'testSQL123abc!@#'
    deployType: 'DacpacTask'
    DeploymentAction: 'Publish'
    DacpacFile: '$(Agent.TempDirectory)'
    IpDetectionMethod: 'AutoDetect'
