resources:
  repositories:
    - repository: BasicDatabaseAutomationTest
      type: github
      endpoint: ranjitk92
      name: ranjitk92/BasicDatabaseAutomationTest

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- checkout: self
- checkout: BasicDatabaseAutomationTest

- task: PowerShell@2
  displayName: Creating clientname and clientvariable pairing
  inputs:
    targetType: 'inline'
    script: 'Install-Module ImportExcel -Scope CurrentUser -Force;$clientvar = Import-Excel **\ClientTestListwithMacro.xlsm | Select-Object -ExpandProperty ClientName;Write-Host "##vso[task.setvariable variable=clientname]$clientvar"'
  enabled: true

- task: AzureResourceManagerTemplateDeployment@3
  displayName: Deploying SQL server, Database, Storage Container, ADF, and Linked Services
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Azure subscription 1(c731920e-f389-4198-98b9-bb54ff8f6bde)'
    subscriptionId: 'c731920e-f389-4198-98b9-bb54ff8f6bde'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'RgPStest'
    location: 'Central US'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/ranjitk92/ARMtemplates/master/QuaXigma_SQLServer_DB_StorageContainer_ADF.json'
    csmParametersFileLink: 'https://raw.githubusercontent.com/ranjitk92/ARMtemplates/master/KeyVaultParameters.json'
    overrideParameters: '-SQLname $(clientname) -DBname $(clientname) -blobstoragecontainer $(clientname) -clienttag $(clientname) -factoryName $(clientname)'
    deploymentMode: 'Incremental'
  enabled: true  

- task: VSBuild@1
  inputs:
    solution: '**\*.sln'
    vsVersion: '16.0'
  enabled: true 

- task: AzureKeyVault@1
  inputs:
    azureSubscription: 'Azure subscription 1(c731920e-f389-4198-98b9-bb54ff8f6bde)'
    KeyVaultName: 'SQLDBlogin'
    SecretsFilter: 'SQLDBlogin'
    RunAsPreJob: false
  enabled: true  

- task: SqlAzureDacpacDeployment@1
  inputs:
    azureSubscription: 'Azure subscription 1(c731920e-f389-4198-98b9-bb54ff8f6bde)'
    AuthenticationType: 'server'
    ServerName: '$(clientname).database.windows.net'
    DatabaseName: '$(clientname)database'
    SqlUsername: 'ranjit1'
    SqlPassword: '$(SQLDBlogin)'
    deployType: 'DacpacTask'
    DeploymentAction: 'Publish'
    DacpacFile: '**\*.dacpac'
    IpDetectionMethod: 'AutoDetect'
  enabled: true