# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- task: PowerShell@2
  displayName: Installing ImportExcel
  inputs:
    targetType: 'inline'
    script: 'Install-Module ImportExcel -Scope CurrentUser -Force'
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: '$clientvariable = Import-Excel $(Build.Repository.LocalPath)\ClientTestListExcel.xlsx | Select-Object -ExpandProperty Name;Write-Host "vso[task.setvariable variable=clientname]$clientvariable"'

