# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'Get-Content -Path $(Build.Repository.LocalPath)/ClientListTest.txt'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      #!/bin/bash
      echo "##vso[task.setvariable variable=clientname;]testvalue"

- task: SqlDacpacDeploymentOnMachineGroup@0
  inputs:
    TaskType: 'sqlInline'
    InlineSql: 'CREATE DATABASE [test]'
    ServerName: 'localhost'
    DatabaseName: 'testdb'
    AuthScheme: 'windowsAuthentication'