# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'Get-Content -Path $(Build.Repository.LocalPath)/ClientListTest.txt'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      #!/bin/bash
      echo "##vso[task.setvariable variable=clientname;]testvalue"

- task: SqlAzureDacpacDeployment@1
  inputs:
    azureSubscription: 'Azure subscription 1(a42ec7cd-86ed-431d-be1a-45fd92b2f25b)'
    AuthenticationType: 'server'
    ServerName: '$(clientname).database.windows.net'
    DatabaseName: '$(clientname)'
    SqlUsername: '$env:LOGIN'
    SqlPassword: '$env:PASSWORD'
    deployType: 'DacpacTask'
    DeploymentAction: 'Import'
    BacpacFile: 'https://databasetestingrk.blob.core.windows.net/databasetestingblob/AdventureWorks2019.bacpac'
    IpDetectionMethod: 'AutoDetect'