# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'Get-Content -Path $(Build.Repository.LocalPath)/ClientListTest.txt'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      #!/bin/bash
      echo "##vso[task.setvariable variable=clientname;]testvalue"

- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Azure subscription 1(a42ec7cd-86ed-431d-be1a-45fd92b2f25b)'
    subscriptionId: 'a42ec7cd-86ed-431d-be1a-45fd92b2f25b'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'RgPStest'
    location: 'East US'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://github.com/ranjitk92/ARMtemplates/blob/master/azuredeploySQLserverandDB.json'
    deploymentMode: 'Incremental'
